# Auto-extracted trail coordinates from trail map
# Generated by tools/extract_trails.py

# === Red (25) ===

# Red_1 — 301px, centroid(4562,2106)
_set_curve(node, "TODO", [
	Vector2(4416, 2068),
	Vector2(4554, 2113),
	Vector2(4716, 2139)
])

# Red_2 — 301px, centroid(4558,2105)
_set_curve(node, "TODO", [
	Vector2(4716, 2137),
	Vector2(4542, 2110),
	Vector2(4416, 2068)
])

# Red_3 — 207px, centroid(2082,2038)
_set_curve(node, "TODO", [
	Vector2(2052, 2008),
	Vector2(2115, 2023),
	Vector2(2114, 2071),
	Vector2(2066, 2069),
	Vector2(2066, 2023)
])

# Red_4 — 206px, centroid(2082,2052)
_set_curve(node, "TODO", [
	Vector2(2052, 2083),
	Vector2(2115, 2069),
	Vector2(2113, 2021),
	Vector2(2068, 2021),
	Vector2(2066, 2070)
])

# Red_5 — 201px, centroid(5446,1704)
_set_curve(node, "TODO", [
	Vector2(5417, 1675),
	Vector2(5477, 1689),
	Vector2(5475, 1737),
	Vector2(5430, 1735),
	Vector2(5431, 1688)
])

# Red_6 — 199px, centroid(5461,1704)
_set_curve(node, "TODO", [
	Vector2(5490, 1675),
	Vector2(5433, 1687),
	Vector2(5430, 1735),
	Vector2(5475, 1737),
	Vector2(5477, 1689)
])

# Red_7 — 198px, centroid(5447,1719)
_set_curve(node, "TODO", [
	Vector2(5417, 1748),
	Vector2(5432, 1688),
	Vector2(5477, 1689),
	Vector2(5478, 1734),
	Vector2(5431, 1736)
])

# Red_8 — 177px, centroid(4998,1810)
_set_curve(node, "TODO", [
	Vector2(4911, 1818),
	Vector2(5085, 1802)
])

# Red_9 — 175px, centroid(3145,1493)
_set_curve(node, "TODO", [
	Vector2(3232, 1487),
	Vector2(3058, 1499)
])

# Red_10 — 175px, centroid(3145,1491)
_set_curve(node, "TODO", [
	Vector2(3058, 1496),
	Vector2(3232, 1487)
])

# Red_11 — 159px, centroid(3395,1417)
_set_curve(node, "TODO", [
	Vector2(3313, 1421),
	Vector2(3403, 1406),
	Vector2(3471, 1426)
])

# Red_12 — 140px, centroid(1419,1597)
_set_curve(node, "TODO", [
	Vector2(1416, 1528),
	Vector2(1423, 1667)
])

# Red_13 — 139px, centroid(1420,1598)
_set_curve(node, "TODO", [
	Vector2(1418, 1529),
	Vector2(1423, 1667)
])

# Red_14 — 134px, centroid(4810,1904)
_set_curve(node, "TODO", [
	Vector2(4885, 1836),
	Vector2(4788, 1936),
	Vector2(4757, 1941)
])

# Red_15 — 123px, centroid(4507,1797)
_set_curve(node, "TODO", [
	Vector2(4568, 1796),
	Vector2(4446, 1799)
])

# Red_16 — 118px, centroid(702,1065)
_set_curve(node, "TODO", [
	Vector2(650, 1007),
	Vector2(754, 1123)
])

# Red_17 — 115px, centroid(4819,1843)
_set_curve(node, "TODO", [
	Vector2(4876, 1828),
	Vector2(4762, 1858)
])

# Red_18 — 111px, centroid(4840,1888)
_set_curve(node, "TODO", [
	Vector2(4795, 1941),
	Vector2(4885, 1836)
])

# Red_19 — 111px, centroid(2087,2033)
_set_curve(node, "TODO", [
	Vector2(2127, 2008),
	Vector2(2067, 2022),
	Vector2(2068, 2069)
])

# Red_20 — 109px, centroid(4352,1782)
_set_curve(node, "TODO", [
	Vector2(4298, 1766),
	Vector2(4406, 1798)
])

# Red_21 — 102px, centroid(2085,2032)
_set_curve(node, "TODO", [
	Vector2(2113, 2026),
	Vector2(2094, 2012),
	Vector2(2067, 2022),
	Vector2(2068, 2069)
])

# Red_22 — 90px, centroid(4516,1874)
_set_curve(node, "TODO", [
	Vector2(4478, 1834),
	Vector2(4555, 1915)
])

# Red_23 — 85px, centroid(3517,1470)
_set_curve(node, "TODO", [
	Vector2(3480, 1431),
	Vector2(3554, 1510)
])

# Red_24 — 72px, centroid(3702,1678)
_set_curve(node, "TODO", [
	Vector2(3737, 1706),
	Vector2(3667, 1651)
])

# Red_25 — 61px, centroid(3610,1588)
_set_curve(node, "TODO", [
	Vector2(3586, 1558),
	Vector2(3634, 1618)
])

# === Green (31) ===

# Green_1 — 293px, centroid(1063,1029)
_set_curve(node, "TODO", [
	Vector2(917, 1005),
	Vector2(1209, 1053)
])

# Green_2 — 244px, centroid(1395,1405)
_set_curve(node, "TODO", [
	Vector2(1413, 1527),
	Vector2(1377, 1284)
])

# Green_3 — 243px, centroid(1397,1405)
_set_curve(node, "TODO", [
	Vector2(1377, 1284),
	Vector2(1418, 1526)
])

# Green_4 — 217px, centroid(3217,1041)
_set_curve(node, "TODO", [
	Vector2(3321, 1020),
	Vector2(3222, 1051),
	Vector2(3110, 1054)
])

# Green_5 — 217px, centroid(2643,1334)
_set_curve(node, "TODO", [
	Vector2(2532, 1332),
	Vector2(2649, 1324),
	Vector2(2748, 1347)
])

# Green_6 — 179px, centroid(2599,868)
_set_curve(node, "TODO", [
	Vector2(2688, 840),
	Vector2(2510, 896)
])

# Green_7 — 171px, centroid(1602,2102)
_set_curve(node, "TODO", [
	Vector2(1602, 2017),
	Vector2(1603, 2187)
])

# Green_8 — 155px, centroid(2075,1684)
_set_curve(node, "TODO", [
	Vector2(2152, 1615),
	Vector2(1999, 1754)
])

# Green_9 — 139px, centroid(2592,1266)
_set_curve(node, "TODO", [
	Vector2(2660, 1211),
	Vector2(2524, 1322)
])

# Green_10 — 133px, centroid(1775,1711)
_set_curve(node, "TODO", [
	Vector2(1841, 1689),
	Vector2(1709, 1734)
])

# Green_11 — 131px, centroid(801,989)
_set_curve(node, "TODO", [
	Vector2(736, 984),
	Vector2(866, 995)
])

# Green_12 — 117px, centroid(2400,928)
_set_curve(node, "TODO", [
	Vector2(2458, 910),
	Vector2(2342, 947)
])

# Green_13 — 117px, centroid(2998,1482)
_set_curve(node, "TODO", [
	Vector2(2941, 1469),
	Vector2(3055, 1495)
])

# Green_14 — 114px, centroid(2997,1484)
_set_curve(node, "TODO", [
	Vector2(3054, 1499),
	Vector2(2941, 1469)
])

# Green_15 — 105px, centroid(670,972)
_set_curve(node, "TODO", [
	Vector2(618, 961),
	Vector2(722, 984)
])

# Green_16 — 103px, centroid(1527,1867)
_set_curve(node, "TODO", [
	Vector2(1529, 1917),
	Vector2(1526, 1817)
])

# Green_17 — 100px, centroid(1746,1769)
_set_curve(node, "TODO", [
	Vector2(1697, 1764),
	Vector2(1796, 1774)
])

# Green_18 — 96px, centroid(1488,1805)
_set_curve(node, "TODO", [
	Vector2(1442, 1800),
	Vector2(1534, 1811)
])

# Green_19 — 93px, centroid(1318,1869)
_set_curve(node, "TODO", [
	Vector2(1358, 1824),
	Vector2(1279, 1915)
])

# Green_20 — 88px, centroid(1541,2198)
_set_curve(node, "TODO", [
	Vector2(1498, 2191),
	Vector2(1585, 2205)
])

# Green_21 — 78px, centroid(1275,1102)
_set_curve(node, "TODO", [
	Vector2(1305, 1138),
	Vector2(1246, 1066)
])

# Green_22 — 73px, centroid(2417,1474)
_set_curve(node, "TODO", [
	Vector2(2451, 1443),
	Vector2(2383, 1506)
])

# Green_23 — 70px, centroid(2771,844)
_set_curve(node, "TODO", [
	Vector2(2773, 812),
	Vector2(2770, 876)
])

# Green_24 — 69px, centroid(2772,846)
_set_curve(node, "TODO", [
	Vector2(2771, 880),
	Vector2(2773, 812)
])

# Green_25 — 69px, centroid(2448,1340)
_set_curve(node, "TODO", [
	Vector2(2414, 1328),
	Vector2(2482, 1352)
])

# Green_26 — 64px, centroid(1925,1679)
_set_curve(node, "TODO", [
	Vector2(1894, 1677),
	Vector2(1957, 1682)
])

# Green_27 — 63px, centroid(3075,1042)
_set_curve(node, "TODO", [
	Vector2(3046, 1031),
	Vector2(3105, 1054)
])

# Green_28 — 63px, centroid(1969,1726)
_set_curve(node, "TODO", [
	Vector2(1972, 1696),
	Vector2(1966, 1757)
])

# Green_29 — 61px, centroid(2473,1389)
_set_curve(node, "TODO", [
	Vector2(2482, 1362),
	Vector2(2464, 1417)
])

# Green_30 — 60px, centroid(2835,1402)
_set_curve(node, "TODO", [
	Vector2(2806, 1379),
	Vector2(2865, 1426)
])

# Green_31 — 60px, centroid(2472,1391)
_set_curve(node, "TODO", [
	Vector2(2463, 1421),
	Vector2(2482, 1362)
])

# === Blue (30) ===

# Blue_1 — 584px, centroid(2057,1075)
_set_curve(node, "TODO", [
	Vector2(1725, 1121),
	Vector2(2157, 1124),
	Vector2(2289, 981)
])

# Blue_2 — 428px, centroid(1460,1086)
_set_curve(node, "TODO", [
	Vector2(1673, 1118),
	Vector2(1247, 1055)
])

# Blue_3 — 389px, centroid(3763,927)
_set_curve(node, "TODO", [
	Vector2(3552, 923),
	Vector2(3798, 920),
	Vector2(3940, 940)
])

# Blue_4 — 287px, centroid(5176,1494)
_set_curve(node, "TODO", [
	Vector2(5019, 1388),
	Vector2(5217, 1506),
	Vector2(5292, 1590)
])

# Blue_5 — 251px, centroid(3378,1047)
_set_curve(node, "TODO", [
	Vector2(3426, 958),
	Vector2(3360, 1001),
	Vector2(3350, 1182)
])

# Blue_6 — 215px, centroid(3157,1390)
_set_curve(node, "TODO", [
	Vector2(3070, 1469),
	Vector2(3134, 1393),
	Vector2(3268, 1308)
])

# Blue_7 — 203px, centroid(660,757)
_set_curve(node, "TODO", [
	Vector2(756, 754),
	Vector2(672, 745),
	Vector2(554, 772)
])

# Blue_8 — 193px, centroid(4216,1136)
_set_curve(node, "TODO", [
	Vector2(4121, 1144),
	Vector2(4312, 1128)
])

# Blue_9 — 191px, centroid(4033,1344)
_set_curve(node, "TODO", [
	Vector2(4043, 1249),
	Vector2(4023, 1439)
])

# Blue_10 — 187px, centroid(4405,1127)
_set_curve(node, "TODO", [
	Vector2(4316, 1126),
	Vector2(4397, 1116),
	Vector2(4502, 1141)
])

# Blue_11 — 184px, centroid(4406,1126)
_set_curve(node, "TODO", [
	Vector2(4319, 1122),
	Vector2(4397, 1116),
	Vector2(4502, 1141)
])

# Blue_12 — 169px, centroid(4418,1129)
_set_curve(node, "TODO", [
	Vector2(4334, 1118),
	Vector2(4502, 1141)
])

# Blue_13 — 150px, centroid(4900,1329)
_set_curve(node, "TODO", [
	Vector2(4826, 1292),
	Vector2(4974, 1366)
])

# Blue_14 — 148px, centroid(5096,1738)
_set_curve(node, "TODO", [
	Vector2(5135, 1777),
	Vector2(5141, 1763),
	Vector2(5013, 1675)
])

# Blue_15 — 142px, centroid(4370,1577)
_set_curve(node, "TODO", [
	Vector2(4301, 1545),
	Vector2(4440, 1610)
])

# Blue_16 — 139px, centroid(4371,1580)
_set_curve(node, "TODO", [
	Vector2(4302, 1550),
	Vector2(4440, 1610)
])

# Blue_17 — 131px, centroid(4106,1630)
_set_curve(node, "TODO", [
	Vector2(4062, 1566),
	Vector2(4151, 1695)
])

# Blue_18 — 130px, centroid(5063,1834)
_set_curve(node, "TODO", [
	Vector2(5127, 1781),
	Vector2(4999, 1887)
])

# Blue_19 — 110px, centroid(1160,1221)
_set_curve(node, "TODO", [
	Vector2(1213, 1236),
	Vector2(1108, 1206)
])

# Blue_20 — 109px, centroid(4102,1057)
_set_curve(node, "TODO", [
	Vector2(4145, 1109),
	Vector2(4060, 1006)
])

# Blue_21 — 108px, centroid(4106,1278)
_set_curve(node, "TODO", [
	Vector2(4107, 1225),
	Vector2(4106, 1332)
])

# Blue_22 — 99px, centroid(865,865)
_set_curve(node, "TODO", [
	Vector2(819, 831),
	Vector2(912, 900)
])

# Blue_23 — 97px, centroid(4629,1600)
_set_curve(node, "TODO", [
	Vector2(4677, 1596),
	Vector2(4581, 1605)
])

# Blue_24 — 97px, centroid(4629,1602)
_set_curve(node, "TODO", [
	Vector2(4677, 1600),
	Vector2(4581, 1605)
])

# Blue_25 — 89px, centroid(4899,1635)
_set_curve(node, "TODO", [
	Vector2(4855, 1624),
	Vector2(4943, 1647)
])

# Blue_26 — 83px, centroid(1204,1029)
_set_curve(node, "TODO", [
	Vector2(1163, 1004),
	Vector2(1245, 1055)
])

# Blue_27 — 79px, centroid(5266,1707)
_set_curve(node, "TODO", [
	Vector2(5301, 1674),
	Vector2(5232, 1740)
])

# Blue_28 — 75px, centroid(4132,1389)
_set_curve(node, "TODO", [
	Vector2(4113, 1352),
	Vector2(4152, 1426)
])

# Blue_29 — 67px, centroid(5300,1639)
_set_curve(node, "TODO", [
	Vector2(5299, 1606),
	Vector2(5302, 1672)
])

# Blue_30 — 66px, centroid(4493,1614)
_set_curve(node, "TODO", [
	Vector2(4526, 1614),
	Vector2(4461, 1615)
])
