# Extracted trail coordinates — paste into path_builder.gd
# Generated by tools/guided_extract.py

	_set_curve(node, "TrailTjorhomGreen1", [
		Vector2(598, 944),
		Vector2(680, 982),
		Vector2(858, 995),
		Vector2(891, 1032),
		Vector2(928, 1010),
		Vector2(1170, 1042),
		Vector2(1254, 1078),
		Vector2(1390, 1249),
		Vector2(1419, 1513),
		Vector2(1353, 1582),
		Vector2(1393, 1633),
		Vector2(1396, 1681),
		Vector2(1344, 1759),
		Vector2(1403, 1807),
		Vector2(1523, 1825),
		Vector2(1530, 1913),
		Vector2(1608, 2065),
		Vector2(1604, 2176),
		Vector2(1557, 2213)
	])

	_set_curve(node, "TrailTjorhomRed1", [
		Vector2(623, 967),
		Vector2(816, 1170),
		Vector2(1408, 1520),
		Vector2(1424, 1660),
		Vector2(1451, 1692),
		Vector2(1440, 1723),
		Vector2(1481, 1800)
	])

	_set_curve(node, "TrailHulderGreen1", [
		Vector2(573, 889),
		Vector2(634, 970),
		Vector2(730, 987)
	])

	_set_curve(node, "TrailNyestolGreen1", [
		Vector2(2785, 789),
		Vector2(2756, 811),
		Vector2(2797, 908),
		Vector2(2905, 962),
		Vector2(2955, 951),
		Vector2(3076, 1062),
		Vector2(2659, 1215),
		Vector2(2487, 1358),
		Vector2(2440, 1453),
		Vector2(2335, 1550),
		Vector2(2162, 1612),
		Vector2(1864, 1859)
	])

	_set_curve(node, "TrailNyestolBlue1", [
		Vector2(2287, 978),
		Vector2(2156, 1120),
		Vector2(2088, 1129)
	])

	_set_curve(node, "TrailNyestolRed1", [
		Vector2(3299, 1427),
		Vector2(3221, 1494),
		Vector2(3139, 1504)
	])

	_set_curve(node, "TrailAlsheiaGreen1", [
		Vector2(3355, 996),
		Vector2(3291, 1035),
		Vector2(3171, 1058)
	])

	_set_curve(node, "TrailAlsheiaRed1", [
		Vector2(3386, 1404),
		Vector2(3494, 1445),
		Vector2(3753, 1720),
		Vector2(4188, 1945),
		Vector2(4344, 2062),
		Vector2(4371, 2051),
		Vector2(4670, 2136)
	])

	_set_curve(node, "TrailConnectNyestolAlsheia", [
		Vector2(2785, 789),
		Vector2(2768, 861),
		Vector2(2793, 905),
		Vector2(2911, 963),
		Vector2(2955, 951),
		Vector2(3005, 1010),
		Vector2(3083, 1051),
		Vector2(2805, 1148),
		Vector2(2771, 1185),
		Vector2(2722, 1179),
		Vector2(2532, 1316),
		Vector2(2738, 1346),
		Vector2(2779, 1391),
		Vector2(2809, 1384),
		Vector2(2908, 1456),
		Vector2(3024, 1498)
	])

	_set_curve(node, "LiftTjorhomChair", [
		Vector2(1003, 1991),
		Vector2(1151, 1185),
		Vector2(1300, 380)
	])

	_set_curve(node, "LiftTjorhomTbar", [
		Vector2(1246, 1946),
		Vector2(1183, 1464),
		Vector2(1121, 982)
	])

	_set_curve(node, "LiftHulderButton", [
		Vector2(606, 2020),
		Vector2(478, 1685),
		Vector2(350, 1350)
	])

	_set_curve(node, "LiftNyestolTbar1", [
		Vector2(2400, 1750),
		Vector2(2375, 1174),
		Vector2(2350, 598)
	])

	_set_curve(node, "LiftNyestolTbar2", [
		Vector2(3006, 1494),
		Vector2(2798, 1060),
		Vector2(2591, 627)
	])

	_set_curve(node, "LiftAlsheiaTbar1", [
		Vector2(3937, 1816),
		Vector2(4002, 1220),
		Vector2(4068, 624)
	])

	_set_curve(node, "LiftAlsheiaTbar2", [
		Vector2(4277, 1734),
		Vector2(4300, 1109),
		Vector2(4323, 484)
	])

	_set_curve(node, "LiftAlsheiaButton", [
		Vector2(4619, 1828),
		Vector2(4647, 1525),
		Vector2(4675, 1222)
	])

	_set_curve(node, "WalkHulderheimen", [
		Vector2(500, 2050),
		Vector2(460, 1950),
		Vector2(420, 1850)
	])

	_set_curve(node, "WalkTjorhom", [
		Vector2(1100, 1950),
		Vector2(1050, 1880),
		Vector2(1000, 1800)
	])

	_set_curve(node, "WalkAlsheia", [
		Vector2(4100, 1880),
		Vector2(4050, 1820),
		Vector2(4000, 1750)
	])
