extends Node2D

## Debug scene: renders all Path2D curves on top of the trail map for visual comparison.
## Run this scene directly to check path accuracy against the real trail map.
##
## Controls:
##   T          - toggle trail map background
##   E          - toggle extracted trail mask overlay (from OpenCV extraction)
##   O          - toggle original PathBuilder paths
##   Tab        - toggle tracing mode (click to place points)
##   Backspace  - undo last traced point
##   Enter      - finish current trace and print GDScript array
##   Escape     - cancel current trace
##   P          - print all current PathBuilder coordinates for comparison
##   S          - save screenshot to res://debug_screenshot.png

var _trail_map_sprite: Sprite2D
var _paths_container: Node2D
var _extracted_overlay: Node2D
var _show_map := true
var _show_extracted := true
var _show_original := true

# Build a difficulty lookup from ResortData once it's initialized
var _trail_colors: Dictionary = {}

# === Tracing mode ===
var _tracing := false
var _traced_points: Array[Vector2] = []
var _trace_line: Line2D
var _trace_dots: Node2D
var _trace_label: Label
var _coord_label: Label  # Shows mouse position


func _ready() -> void:
	# Trail map background
	_trail_map_sprite = Sprite2D.new()
	_trail_map_sprite.texture = load("res://assets/images/trail_map.png")
	_trail_map_sprite.centered = false
	add_child(_trail_map_sprite)

	# Build paths container hierarchy (same structure as main.tscn)
	_paths_container = Node2D.new()
	_paths_container.name = "PathsContainer"
	var lifts_node := Node2D.new()
	lifts_node.name = "Lifts"
	var trails_node := Node2D.new()
	trails_node.name = "Trails"
	var walks_node := Node2D.new()
	walks_node.name = "WalkPaths"
	_paths_container.add_child(lifts_node)
	_paths_container.add_child(trails_node)
	_paths_container.add_child(walks_node)
	add_child(_paths_container)

	# Build all Path2D curves
	PathBuilder.build_all_paths(_paths_container)

	# Build trail color lookup from ResortData
	_build_trail_color_lookup()

	# Draw colored lines on top of each path
	_draw_lift_lines(lifts_node)
	_draw_trail_lines(trails_node)
	_draw_walk_lines(walks_node)

	# Extracted trail mask overlay (from OpenCV color extraction)
	_extracted_overlay = Node2D.new()
	_extracted_overlay.z_index = 5  # Between map (0) and PathBuilder lines (10)
	add_child(_extracted_overlay)
	_load_extracted_masks()

	# Tracing overlay (hidden until Tab)
	_trace_dots = Node2D.new()
	_trace_dots.z_index = 20
	add_child(_trace_dots)

	_trace_line = Line2D.new()
	_trace_line.width = 3.0
	_trace_line.default_color = Color.YELLOW
	_trace_line.z_index = 19
	add_child(_trace_line)

	# HUD labels (screen-space via CanvasLayer)
	var hud := CanvasLayer.new()
	add_child(hud)

	_trace_label = Label.new()
	_trace_label.position = Vector2(10, 10)
	_trace_label.add_theme_font_size_override("font_size", 18)
	_trace_label.add_theme_color_override("font_color", Color.YELLOW)
	_trace_label.add_theme_color_override("font_outline_color", Color.BLACK)
	_trace_label.add_theme_constant_override("outline_size", 4)
	_trace_label.text = "T=map | E=extracted | O=original | Tab=trace | S=screenshot"
	hud.add_child(_trace_label)

	_coord_label = Label.new()
	_coord_label.position = Vector2(10, 40)
	_coord_label.add_theme_font_size_override("font_size", 16)
	_coord_label.add_theme_color_override("font_color", Color.WHITE)
	_coord_label.add_theme_color_override("font_outline_color", Color.BLACK)
	_coord_label.add_theme_constant_override("outline_size", 3)
	hud.add_child(_coord_label)


func _load_extracted_masks() -> void:
	# Load mask PNGs generated by tools/extract_trails.py and overlay with color tint.
	# Uses a shader to map white mask pixels → tinted color, black → transparent.
	var mask_shader := _create_mask_shader()

	var masks: Array[Dictionary] = [
		{"file": "res://debug_mask_red.png", "color": Color(1, 0.15, 0.15)},
		{"file": "res://debug_mask_green.png", "color": Color(0.15, 1, 0.15)},
		{"file": "res://debug_mask_blue.png", "color": Color(0.3, 0.6, 1.0)},
	]
	for mask_info in masks:
		var path: String = mask_info["file"]
		if not FileAccess.file_exists(path):
			print("Mask not found: %s (run: python3 tools/extract_trails.py --debug)" % path)
			continue
		var tex := ImageTexture.create_from_image(Image.load_from_file(path))
		var sprite := Sprite2D.new()
		sprite.texture = tex
		sprite.centered = false
		var mat := ShaderMaterial.new()
		mat.shader = mask_shader
		mat.set_shader_parameter("tint_color", mask_info["color"])
		mat.set_shader_parameter("alpha_strength", 0.8)
		sprite.material = mat
		_extracted_overlay.add_child(sprite)
		print("Loaded extracted mask: %s" % path)


static func _create_mask_shader() -> Shader:
	var shader := Shader.new()
	shader.code = "
shader_type canvas_item;
uniform vec3 tint_color : source_color = vec3(1.0, 0.0, 0.0);
uniform float alpha_strength : hint_range(0.0, 1.0) = 0.8;
void fragment() {
	float brightness = texture(TEXTURE, UV).r;
	COLOR = vec4(tint_color, brightness * alpha_strength);
}
"
	return shader


func _build_trail_color_lookup() -> void:
	for trail in ResortData.trails:
		match trail.difficulty:
			TrailDefinition.Difficulty.GREEN:
				_trail_colors[trail.path_node_name] = Color.GREEN
			TrailDefinition.Difficulty.BLUE:
				_trail_colors[trail.path_node_name] = Color.DODGER_BLUE
			TrailDefinition.Difficulty.RED:
				_trail_colors[trail.path_node_name] = Color.RED


func _draw_lift_lines(lifts_node: Node2D) -> void:
	for child in lifts_node.get_children():
		if child is Path2D:
			_create_line_from_path(child, Color.DARK_GRAY, 4.0)


func _draw_trail_lines(trails_node: Node2D) -> void:
	for child in trails_node.get_children():
		if child is Path2D:
			var color: Color
			if child.name in _trail_colors:
				color = _trail_colors[child.name]
			elif child.name.begins_with("TrailConnect"):
				color = Color.ORANGE
			else:
				color = Color.WHITE
			_create_line_from_path(child, color, 5.0)


func _draw_walk_lines(walks_node: Node2D) -> void:
	for child in walks_node.get_children():
		if child is Path2D:
			_create_line_from_path(child, Color.SADDLE_BROWN, 2.0)


func _create_line_from_path(path: Path2D, color: Color, width: float) -> void:
	var curve := path.curve
	if curve == null or curve.point_count < 2:
		return

	var line := Line2D.new()
	line.width = width
	line.default_color = color
	line.z_index = 10
	line.antialiased = true

	var baked_length := curve.get_baked_length()
	var num_samples := 100
	for i in range(num_samples + 1):
		var offset := (float(i) / num_samples) * baked_length
		line.add_point(curve.sample_baked(offset))

	path.get_parent().add_child(line)

	# Labels at start and end
	_add_label(path.name, curve.get_point_position(0) + Vector2(0, -15), color)
	_add_label(path.name, curve.get_point_position(curve.point_count - 1) + Vector2(0, 15), color)


func _add_label(text: String, pos: Vector2, color: Color) -> void:
	var label := Label.new()
	label.text = text
	label.position = pos - Vector2(50, 10)
	label.add_theme_font_size_override("font_size", 14)
	label.add_theme_color_override("font_color", color)
	label.add_theme_color_override("font_outline_color", Color.BLACK)
	label.add_theme_constant_override("outline_size", 3)
	label.z_index = 11
	add_child(label)


func _process(delta: float) -> void:
	var mouse_pos := get_global_mouse_position()
	_coord_label.text = "Map coords: (%d, %d)" % [roundi(mouse_pos.x), roundi(mouse_pos.y)]

	# Auto-screenshot for CLI: godot ... -- --auto-screenshot
	if not _auto_done and "--auto-screenshot" in OS.get_cmdline_user_args():
		_auto_timer += delta
		if _auto_timer > 1.0:
			_auto_done = true
			_take_auto_screenshot()


func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed:
		match event.keycode:
			KEY_T:
				_show_map = not _show_map
				_trail_map_sprite.visible = _show_map
			KEY_E:
				_show_extracted = not _show_extracted
				_extracted_overlay.visible = _show_extracted
				_trace_label.text = "Extracted masks: %s" % ("ON" if _show_extracted else "OFF")
			KEY_O:
				_show_original = not _show_original
				_paths_container.visible = _show_original
				_trace_label.text = "Original paths: %s" % ("ON" if _show_original else "OFF")
			KEY_TAB:
				_tracing = not _tracing
				if _tracing:
					_traced_points.clear()
					_trace_line.clear_points()
					_clear_trace_dots()
					_trace_label.text = "TRACING: Click to place points | Backspace=undo | Enter=finish | Esc=cancel"
				else:
					_trace_label.text = "T=map | E=extracted | O=original | Tab=trace | S=screenshot"
			KEY_BACKSPACE:
				if _tracing and _traced_points.size() > 0:
					_traced_points.pop_back()
					_rebuild_trace_visuals()
			KEY_ENTER:
				if _tracing and _traced_points.size() >= 2:
					_print_traced_points()
					_tracing = false
					_trace_label.text = "Trace printed to console. Press Tab to trace another."
			KEY_ESCAPE:
				if _tracing:
					_traced_points.clear()
					_trace_line.clear_points()
					_clear_trace_dots()
					_tracing = false
					_trace_label.text = "Trace cancelled. Press Tab to start again."
			KEY_P:
				_print_all_paths()
			KEY_S:
				_save_screenshot()

	# Click to place trace points
	if _tracing and event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		var world_pos := get_global_mouse_position()
		var snapped := Vector2(roundi(world_pos.x), roundi(world_pos.y))
		_traced_points.append(snapped)
		_rebuild_trace_visuals()
		_trace_label.text = "TRACING: %d points | Click=add | Backspace=undo | Enter=finish" % _traced_points.size()


func _rebuild_trace_visuals() -> void:
	_trace_line.clear_points()
	_clear_trace_dots()
	for pt in _traced_points:
		_trace_line.add_point(pt)
		_add_trace_dot(pt)


func _add_trace_dot(pos: Vector2) -> void:
	var dot := Sprite2D.new()
	# Create a small circle texture
	var img := Image.create(12, 12, false, Image.FORMAT_RGBA8)
	img.fill(Color.YELLOW)
	dot.texture = ImageTexture.create_from_image(img)
	dot.position = pos
	dot.z_index = 21
	_trace_dots.add_child(dot)


func _clear_trace_dots() -> void:
	for child in _trace_dots.get_children():
		child.queue_free()


func _print_traced_points() -> void:
	# Print as a ready-to-paste GDScript array
	var lines := PackedStringArray()
	lines.append("# Traced %d points — paste into PathBuilder:" % _traced_points.size())
	lines.append("[")
	for i in range(_traced_points.size()):
		var pt := _traced_points[i]
		var comma := "," if i < _traced_points.size() - 1 else ""
		lines.append("\tVector2(%d, %d)%s" % [roundi(pt.x), roundi(pt.y), comma])
	lines.append("]")
	var output := "\n".join(lines)
	print(output)
	# Also save to file for easy access
	var file := FileAccess.open("res://traced_path.txt", FileAccess.WRITE)
	if file:
		file.store_string(output)
		file.close()
		print("Also saved to res://traced_path.txt")


func _print_all_paths() -> void:
	print("\n=== Current PathBuilder paths vs map ===")
	for category in ["Lifts", "Trails", "WalkPaths"]:
		var node := _paths_container.get_node(category)
		for child in node.get_children():
			if child is Path2D and child.curve:
				var pts := PackedStringArray()
				for i in range(child.curve.point_count):
					var p: Vector2 = child.curve.get_point_position(i)
					pts.append("Vector2(%d, %d)" % [roundi(p.x), roundi(p.y)])
				print("%s: [%s]" % [child.name, ", ".join(pts)])


var _auto_timer := 0.0
var _auto_done := false

func _save_screenshot() -> void:
	await RenderingServer.frame_post_draw
	var img := get_viewport().get_texture().get_image()
	img.save_png("res://debug_screenshot.png")
	print("Screenshot saved to res://debug_screenshot.png")
	_trace_label.text = "Screenshot saved!"


func _take_auto_screenshot() -> void:
	await RenderingServer.frame_post_draw
	var img := get_viewport().get_texture().get_image()
	img.save_png("res://debug_screenshot.png")
	print("Auto-screenshot saved")
	get_tree().quit()
